/*
 * File:           E:\adau-1787-dsp-program\adau_1787_IC_1_SIGMA_PARAM.h
 *
 * Created:        Tuesday, September 17, 2024 5:56:29 PM
 * Description:    adau_1787:IC 1-Sigma parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2024 Analog Devices, Inc. All rights reserved.
 */
#ifndef __ADAU_1787_IC_1_SIGMA_PARAM_H__
#define __ADAU_1787_IC_1_SIGMA_PARAM_H__


/* Module Non Modulo Location Start - Non Modulo Location Start*/
#define MOD_NONMODULOLOCATIONSTART_COUNT               1
#define MOD_NONMODULOLOCATIONSTART_DEVICE              "IC1_Sigma"
#define MOD_NONMODULOLOCATIONSTART_NON_MODULO_LOCATION_START_ADDR 8192
#define MOD_NONMODULOLOCATIONSTART_NON_MODULO_LOCATION_START_FIXPT 0x000007FF
#define MOD_NONMODULOLOCATIONSTART_NON_MODULO_LOCATION_START_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(2047)
#define MOD_NONMODULOLOCATIONSTART_NON_MODULO_LOCATION_START_TYPE SIGMASTUDIOTYPE_INTEGER

/* Module SafeLoadModule - SafeLoadModule*/
#define MOD_SAFELOADMODULE_COUNT                       7
#define MOD_SAFELOADMODULE_DEVICE                      "IC1_Sigma"
#define MOD_SAFELOADMODULE_DATALOADSTART_SAFELOAD_ADDR 8196
#define MOD_SAFELOADMODULE_DATALOAD1_SAFELOAD_ADDR     8200
#define MOD_SAFELOADMODULE_DATALOAD2_SAFELOAD_ADDR     8204
#define MOD_SAFELOADMODULE_DATALOAD3_SAFELOAD_ADDR     8208
#define MOD_SAFELOADMODULE_DATALOADEND_SAFELOAD_ADDR   8212
#define MOD_SAFELOADMODULE_ADDRESSLOAD_SAFELOAD_ADDR   8216
#define MOD_SAFELOADMODULE_NUMLOAD_SAFELOAD_ADDR       8220

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COUNT       1
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_DEVICE      "IC1_Sigma"
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COEFFICIENT_OFFSET_LOCATION_START_ADDR 8224
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COEFFICIENT_OFFSET_LOCATION_START_FIXPT 0x00002004
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COEFFICIENT_OFFSET_LOCATION_START_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(8196)
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COEFFICIENT_OFFSET_LOCATION_START_TYPE SIGMASTUDIOTYPE_INTEGER

/* Module Level1 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL1_COUNT                               3
#define MOD_LEVEL1_DEVICE                              "IC1_Sigma"
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_ADDR 8228
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_FIXPT 0x00004EB0
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00240140490349172)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_ADDR 8232
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_FIXPT 0x000001E0
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_ADDR 8236
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_FIXPT 0x0000071C
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000217013888888889)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Single 1 - Single Volume Shared*/
#define MOD_SINGLE1_COUNT                              3
#define MOD_SINGLE1_DEVICE                             "IC1_Sigma"
#define MOD_SINGLE1_ALG0_TARGETGAINGAINS200ALGGROWSTEP1_ADDR 8256
#define MOD_SINGLE1_ALG0_TARGETGAINGAINS200ALGGROWSTEP1_FIXPT 0x00800000
#define MOD_SINGLE1_ALG0_TARGETGAINGAINS200ALGGROWSTEP1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SINGLE1_ALG0_TARGETGAINGAINS200ALGGROWSTEP1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SINGLE1_ALG0_STEPSIZEGAINS200ALGGROWSTEP1_ADDR 8260
#define MOD_SINGLE1_ALG0_STEPSIZEGAINS200ALGGROWSTEP1_FIXPT 0x00000053
#define MOD_SINGLE1_ALG0_STEPSIZEGAINS200ALGGROWSTEP1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1E-05)
#define MOD_SINGLE1_ALG0_STEPSIZEGAINS200ALGGROWSTEP1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SINGLE1_ALG0_CURRENTGAINGAINS200ALGGROWSTEP1_ADDR 8264
#define MOD_SINGLE1_ALG0_CURRENTGAINGAINS200ALGGROWSTEP1_FIXPT 0x00000000
#define MOD_SINGLE1_ALG0_CURRENTGAINGAINS200ALGGROWSTEP1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SINGLE1_ALG0_CURRENTGAINGAINS200ALGGROWSTEP1_TYPE SIGMASTUDIOTYPE_FIXPOINT

#endif
