/*
 * File:           C:\users\crossover\Desktop\exports\adau_1787_IC_1_SIGMA_PARAM.h
 *
 * Created:        Monday, May 18, 2026 11:16:45 PM
 * Description:    adau_1787:IC 1-Sigma parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2026 Analog Devices, Inc. All rights reserved.
 */
#ifndef __ADAU_1787_IC_1_SIGMA_PARAM_H__
#define __ADAU_1787_IC_1_SIGMA_PARAM_H__

/* Module Non Modulo Location Start - Non Modulo Location Start*/
#define MOD_NONMODULOLOCATIONSTART_COUNT 1
#define MOD_NONMODULOLOCATIONSTART_DEVICE "IC1_Sigma"
#define MOD_NONMODULOLOCATIONSTART_NON_MODULO_LOCATION_START_ADDR 8192
#define MOD_NONMODULOLOCATIONSTART_NON_MODULO_LOCATION_START_FIXPT 0x000007FE
#define MOD_NONMODULOLOCATIONSTART_NON_MODULO_LOCATION_START_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(2046)
#define MOD_NONMODULOLOCATIONSTART_NON_MODULO_LOCATION_START_TYPE SIGMASTUDIOTYPE_INTEGER

/* Module SafeLoadModule - SafeLoadModule*/
#define MOD_SAFELOADMODULE_COUNT 7
#define MOD_SAFELOADMODULE_DEVICE "IC1_Sigma"
#define MOD_SAFELOADMODULE_DATALOADSTART_SAFELOAD_ADDR 8196
#define MOD_SAFELOADMODULE_DATALOAD1_SAFELOAD_ADDR 8200
#define MOD_SAFELOADMODULE_DATALOAD2_SAFELOAD_ADDR 8204
#define MOD_SAFELOADMODULE_DATALOAD3_SAFELOAD_ADDR 8208
#define MOD_SAFELOADMODULE_DATALOADEND_SAFELOAD_ADDR 8212
#define MOD_SAFELOADMODULE_ADDRESSLOAD_SAFELOAD_ADDR 8216
#define MOD_SAFELOADMODULE_NUMLOAD_SAFELOAD_ADDR 8220

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COUNT 1
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_DEVICE "IC1_Sigma"
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COEFFICIENT_OFFSET_LOCATION_START_ADDR 8224
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COEFFICIENT_OFFSET_LOCATION_START_FIXPT 0x00002004
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COEFFICIENT_OFFSET_LOCATION_START_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(8196)
#define MOD_COEFFICIENTOFFSETLOCATIONSTART_COEFFICIENT_OFFSET_LOCATION_START_TYPE SIGMASTUDIOTYPE_INTEGER

/* Module Final Volume - Single Volume Shared*/
#define MOD_FINALVOLUME_COUNT 3
#define MOD_FINALVOLUME_DEVICE "IC1_Sigma"
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1GAINTARGET_ADDR 8228
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1GAINTARGET_FIXPT 0x00800000
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1GAINTARGET_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1GAINTARGET_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1ALPHA0_ADDR 38904
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1ALPHA0_FIXPT 0x007FF259
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1ALPHA0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.999583420126834)
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1ALPHA0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1ALPHA1_ADDR 38905
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1ALPHA1_FIXPT 0x00000DA6
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1ALPHA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000416579873166234)
#define MOD_FINALVOLUME_ALG0_GAINS200ALGGROWDP1ALPHA1_TYPE SIGMASTUDIOTYPE_FIXPOINT

#endif
